# Generated by Django 6.0.4 on 2026-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Herb', 'Herb'), ('Flower', 'Flower'), ('Tree', 'Tree')], max_length=50)),
                ('is_edible', models.BooleanField(default=False)),
                ('image', models.ImageField(default='plant_images/default.jpg', upload_to='plant_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
